# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TBMessageDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

    pod 'TBMessage', :git => 'https://github.com/FJust/TBMessage.git'

  # Pods for TBMessageDemo

end
